# Generated by Django 5.1.1 on 2024-10-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinDiseaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindisease',
            name='disease_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skindisease',
            name='read_more',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skindisease',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
