# Generated by Django 5.1.1 on 2024-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinDiseaseApp', '0002_skindisease_disease_ar_skindisease_read_more_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skindisease',
            name='model_class_num',
            field=models.IntegerField(default=0),
        ),
    ]
