# Generated by Django 5.1.1 on 2024-10-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_imageupload'),
        ('SkinDiseaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image_url',
            field=models.URLField(default='noImage'),
        ),
        migrations.RemoveField(
            model_name='history',
            name='skin_diseases',
        ),
        migrations.AddField(
            model_name='history',
            name='skin_diseases',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SkinDiseaseApp.skindisease'),
            preserve_default=False,
        ),
    ]
